### ISSUE TITLE
Useragent Required

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-plugin-opensubtitles#1]
Hey 👋 
OpenSubtitles requires us to use a specific useragent to identify the app. It must be in the format we have registered with them, and a version number.

In this case, the appropriate useragent would be `Jellyfin v10.2`.

**Comment by hawken93** [comment]
Isn't it better to go with jellyfin v10, the smaller version numbers shouldn't matter that much and it has to try tracking the main program.. Maybe the core can provide the plugins with an appropriate user agent? :)

**Comment by nvllsvm** [comment]
Can we register a User-Agent per [RFC 2616](https://tools.ietf.org/html/rfc2616#section-14.43)? The value `Jellyfin/10.2` would be more appropriate.

**Comment by anthonylavado** [comment]
It’s not a useragent in the traditional sense. This is an OpenSubtitles required construct, it’s how they identify that we are an authorized program.

They require it to be in the format `AppName vXY.Z`, where leading zeroes can be omitted if desired, and the Z can be removed if desired.

**Comment by anthonylavado** [comment]
See here for details: http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst

**Comment by anthonylavado** [comment]
I suppose like Emby before us, we could omit version entirely.

**Comment by hawken93** [comment]
After reading this I still stand by using Jellyfin v10. Major version and even program name can be read from the core program to be robust against version changes and even rebranding, the goal being to write code that lasts a long time :)

**Comment by anthonylavado** [comment]
@hawken93 That’s fine. It sounds good to me.
