### ISSUE TITLE
API rate limit 429 too many requests 

### ISSUE THREAD

**Issue by flyer280** [jellyfin/jellyfin-plugin-opensubtitles#10]
Per https://forum.opensubtitles.org/viewtopic.php?t=16072
rate limit of 40 per 10 seconds per IP also includes a "RateLimit-Remaining" bucket.

Need to slow down the requests on machines that can process them faster than 40 per 10 seconds. And/or do them in bursts and stop before the limit and retry the last one that was denied after the limit is reset.

**Comment by jaredallard** [comment]
You could also naively just delay for X amount of time whenever a 429 occurs instead of adding burst / retry last logic
