### ISSUE TITLE
[Request] Add Chinese Bilingual as an option

### ISSUE THREAD

**Issue by pewter77** [jellyfin/jellyfin-plugin-opensubtitles#103]
Not sure if this is something that would need to be added into Jellyfin as well as here. OpenSubtitles.org not sure if .com supports dual subtitles for chinese.

Could be as simple as searching Chinese subs and Chinese Bilingual at the same time (which would be nice actually) or a separate one.

Bilingual Household and dual subs are really nice to have, they're common with Chinese/English fortunately.

**Comment by MBR-0001** [comment]
Opensubtitles supports it but jellyfin does not, the language needs to be added to the [language list](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Localization/iso6392.txt)

as far as I know nothing would have to be changed in the plugin
