### ISSUE TITLE
OpenSubs API Key ServiceUnavailable

### ISSUE THREAD

**Issue by Chillsmeit** [jellyfin/jellyfin-plugin-opensubtitles#110]
I've been setting up Jellyfin and unfortunately I'm unable to set up the OpenSubs plugin. 
Whenever I enter my credentials and/or use the API I created on the website, I get "Request failed - ServiceUnavailable" every time.
The API Status also shows as being down too. Not sure if it's temporary and something to do with the new API OpenSubs is using

**Comment by crobibero** [comment]
This isnt something we can fix. Try again when the API is back up.
