### ISSUE TITLE
Service Unavailable Error

### ISSUE THREAD

**Issue by frostywite** [jellyfin/jellyfin-plugin-opensubtitles#113]
Plugin stopped working around on the 22nd of December. Verified account, saved user name and password, plugin says verified and allowed to download 20 subs a day. Deleted plugin and reinstalled still says service unavailable. Error varnish cache server 503.

 "2023-01-02 06:34:47.184 -08:00] [ERR] [21] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Invalid response: ServiceUnavailable - "<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 19202345</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
"
[2023-01-02 06:35:56.482 -08:00] [ERR] [27] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Invalid response: ServiceUnavailable - "<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 860101133</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
"

**Comment by crobibero** [comment]
There isnt anything we can do if Trakts api is down.

**Comment by frostywite** [comment]
Thanks Corbibero, That's what I thought, but was not sure, said on twitter it was back up mid December and I had downloads on the 22nd. I'll keep waiting.
