### ISSUE TITLE
[Issue]: Subtitles added to queue but are not downloaded

### ISSUE THREAD

**Issue by DonManoloCelete** [jellyfin/jellyfin-plugin-opensubtitles#116]
### Please describe your bug

I'm using the opensubtitles plugin. However when I want to download a subtitle for an individual movie, it says the download is being queued. However I can't seem to find any queue and the subtitle doesn't download at all.
When I try to force the scheduled task to download missing subtitles nothing happens either. 

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Windows
- Virtualization:/
- Clients:Browser
- Browser:Firefox 91
- FFmpeg Version:/
- Playback Method:/
- Hardware Acceleration:/
- Plugins:Opensubtitles.com
- Reverse Proxy:/
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MBR-0001** [comment]
The queued download message is actually misleading, that message shows up after successfully downloading subtitles (afaik), can you check logs for subtitle-related entries?

**Comment by DonManoloCelete** [comment]
Thanks for answering. There aren't any log files related to subtitles and the subtitles are still not being downloaded unfortunately.

**Comment by DonManoloCelete** [comment]
Hi, I didn't manage to enable debug logging. However, it seems my problem has been resolved. The subtitles are being downloaded now. I have no idea how this has happened, I didn't change anything...

**Comment by Arutosio** [comment]
up

**Comment by Ckankonmange** [comment]
For those getting on this thread thanks to Google, I had the same error, enabled the logs and the error was pretty obvious :

[2025-05-26 19:55:36.312 +00:00] [ERR] [57] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
MediaBrowser.Common.Extensions.RateLimitExceededException: **OpenSubtitles download limit reached**
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetSubtitlesInternal(String id, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)

Can message be changed to reflect the error ?

**Comment by surrogatpappan** [comment]
I'm from the future of the year 2026 and I've come to bump this thread.
Can message be changed to reflect the error ?
