### ISSUE TITLE
[opensubtitles] Contact us

### ISSUE THREAD

**Issue by opensubtitles** [jellyfin/jellyfin-plugin-opensubtitles#127]
We had to disable your useragent, please contact us to solve this issue

Thanks

**Comment by anthonylavado** [comment]
@opensubtitles I'll be sending an e-mail to you shortly.

**Comment by anthonylavado** [comment]
@opensubtitles Are you able to respond to my email?

Thanks,
Anthony

**Comment by opensubtitles** [comment]
@anthonylavado sure, but I can not find it, please send again (or via our contact form). Thanks.
