### ISSUE TITLE
Refresh the view when a subtitle track has finished downloading

### ISSUE THREAD

**Issue by shadow7412** [jellyfin/jellyfin-plugin-opensubtitles#135]
From both the web and android app, the only way to actually select the new subtitle track if it didn't have any originally seems to be to leave the episode screen and go back into it.

Is there a way we can have the screen automatically update with this to avoid having to keep checking it?

On the subject of QOL fixes, could we have the search run automatically when there aren't any subtitle tracks to save a click?

**Comment by crobibero** [comment]
Neither of these are possible with the plug-in. Both are feature requests. See if they exist here: https://features.jellyfin.org/

**Comment by shadow7412** [comment]
Shame. Thanks for letting me know.
