### ISSUE TITLE
Can't Sign in to plugin: Request failed - BadGateway

### ISSUE THREAD

**Issue by roydbt** [jellyfin/jellyfin-plugin-opensubtitles#140]
I've downloaded the plugin (v19), and when I try to sign in I get a pop up saying only "Request failed - BadGateway".
I am using the docker version of Jellyfin on a raspberry pi 5 (I know the documentation warned against it), and the logs says nothing about this error.

**Comment by crobibero** [comment]
Likely means the api is down. Try again later.
