### ISSUE TITLE
Plugin doesn't find subtitles - but they do exist on the website

### ISSUE THREAD

**Issue by Obegg** [jellyfin/jellyfin-plugin-opensubtitles#141]
It appears as though the OpenSubtitles plugin (which is updated to the latest):
![image](https://github.com/jellyfin/jellyfin-plugin-opensubtitles/assets/13978119/0bbdb670-1fa6-4317-8821-742981fe929f)

Can't seem to find subtitles for a TV series:
![image](https://github.com/jellyfin/jellyfin-plugin-opensubtitles/assets/13978119/0126d773-7150-45c1-b3bf-f1a8cfe2650c)

But there is a subtitle available to download from OpenSubtitles.org:
https://www.opensubtitles.org/en/subtitles/9910293/one-day-episode-1-1-he

Why doesn't this plugin find it and downloads it?

**Comment by MBR-0001** [comment]
Are you able to find that subtitle on https://opensubtitles.com ?
The plugin uses the new API which pulls subtitles from the .com site, not .org.
Those two should have identical subtitles but sometimes due to issues in their systems they don't.

**Comment by MBR-0001** [comment]
can you try turning on debug logging https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging and searching for the subtitles? it should log something like `search query: { (stuff here) }`

**Comment by MBR-0001** [comment]
> Is there any way to counter this specific issue with the subtitles not showing up on .com?

Well, you could notify them on their forum https://forum.opensubtitles.org/ or through the contact form https://www.opensubtitles.com/en/contact/, they usually solve this quite quickly
