### ISSUE TITLE
Force subtitles download for individual show or season

### ISSUE THREAD

**Issue by Betonhaus** [jellyfin/jellyfin-plugin-opensubtitles#144]
There should be a way when you're looking at a show that you just added where you could force jellyfin to start finding and downloading subtitles for the whole show, or just one season. instead of having to click each episode one by one and download the subtitles. ideally t would let you choose between all close matches for each episode, but even automatically downloading would still be an improvement

**Comment by crobibero** [comment]
This is a Jellyfin feature request and not a plugin feature request.

**Comment by Betonhaus** [comment]
i see great strides have been made in resolving the bureaucratic nightmare development has been

may I ask which repository I should be directing my question to? as last time I was batted between three different repositories before one took ownership after the other two said they weren't responsible
