### ISSUE TITLE
Make it possible to save subtitles at movie location

### ISSUE THREAD

**Issue by Kicer86** [jellyfin/jellyfin-plugin-opensubtitles#156]
As of now subtitles are being downloaded to jellyfin's internal locations. 
I'd prefer to keep subtitles along with movie file.

Please add an option to allow that

**Comment by MBR-0001** [comment]
This already exists (under library options)
![Image](https://github.com/user-attachments/assets/8ef9a1a5-2578-4600-9cb7-12996075790b)

**Comment by Kicer86** [comment]
I had it checked.
But I discovered that I had no proper write permissions for directory with movie.
