### ISSUE TITLE
OpenSubtitles domain not working in Denmark

### ISSUE THREAD

**Issue by ALharchi** [jellyfin/jellyfin-plugin-opensubtitles#21]
Hello,

I have my server hosted in Denmark, and the Opensubtitles plugin is not working. When you go to opensubtitles.org it redirects you to the following document:

https://rettighedsalliancen.dk/wp-content/uploads/2018/03/Frederiksberg-District-Court-RA-v-TDC-5-December-2017-Popcorn-Time-EN.pdf

TDC (one of the biggest providers in the country) blocked access to that domain (and others) and therefore the plugin is not working. 

Not sure what would be the best solution (besides wrapping everything behind a VPN)..

What do you think?

Thanks!

**Comment by anthonylavado** [comment]
@ALharchi We don’t have any other providers at the moment, but you can always add subtitles manually.

At any rate, I’m reading that there are a lot of users who say it is a block at the DNS level, not a geoblock from OpenSubtitles. Apparently, if you try setting a different DNS server, it should work. I can personally recommend https://1.1.1.1
:-)

**Comment by ellidi** [comment]
> @ALharchi We don’t have any other providers at the moment, but you can always add subtitles manually.
> 
> At any rate, I’m reading that there are a lot of users who say it is a block at the DNS level, not a geoblock from OpenSubtitles. Apparently, if you try setting a different DNS server, it should work. I can personally recommend https://1.1.1.1
> :-)

It is not a block at the DNS level.
Apparently OpenSubtitles have redirected traffic from all Danish IP addresses to this PDF :/ 
I know this is solved by using a VPN, but it's annoying :)

**Comment by dkanada** [comment]
We're definitely not in the business of providing VPN services so I guess this doesn't really have a solution unless someone adds proxy support to our HTTP client on the server.
