### ISSUE TITLE
Manually add subtitles

### ISSUE THREAD

**Issue by jee-r** [jellyfin/jellyfin-plugin-opensubtitles#31]
Hello,

I'm forwarding this [issue](https://github.com/jellyfin/jellyfin/issues/2026
) / [feature request](https://features.jellyfin.org/posts/324/manually-add-subtitles) here because i think that add this option on the opensubtitles plugin can be a good workaround instead of implement it in jellyfin core

Thank you

**Comment by Ullmie02** [comment]
As this feature has been implemented in the core server, I don't think we need it in the plugin as well ;)
