### ISSUE TITLE
[REQUEST] Allow choose between 2 or 3 letter language tags

### ISSUE THREAD

**Issue by MartenBE** [jellyfin/jellyfin-plugin-opensubtitles#60]
When asking a subtitle for movie.mp4, the subtitle will be named movie.eng.srt. I was wondering if it were possible to let it output 2 letter country codes so it would be movie.en.srt? This would allow it to work better together with tools as https://github.com/Diaoul/subliminal . The use of 2-letter codes is also more appropriate with BCP 47 [1][2]

[1] https://www.w3.org/International/questions/qa-lang-2or3 "_Should I use two-letter or three-letter ISO language codes in language tags?_"
[2] https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by MBR-0001** [comment]
I believe this should be moved to the jellyfin server repo since it is the one that [controls this](https://github.com/jellyfin/jellyfin/blob/e15fea5dade9478d9667399eb0c245917d3e1513/MediaBrowser.Providers/Subtitles/SubtitleManager.cs#L196)

**Comment by Vince0511** [comment]
I know this is an old post, but it's still open. I'm still experiancing this issue.
When I download subtitles with the opensubtitles plugin, they get a 3-letter tag.
For use with other tools I'm looking for a 2-letter tag. (for example: en, nl, sv in stead of eng, dut, swe)

**Comment by MBR-0001** [comment]
@crobibero could this be moved to the main server repo?

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org/ and not in the server repo, so closing.
