### ISSUE TITLE
The OpenSubtitle task should stop when the prescribed number of downloads is reached. 

### ISSUE THREAD

**Issue by develroo** [jellyfin/jellyfin-plugin-opensubtitles#63]
Self-explanatory really. The plugin now correctly reports the amount of downloads left. 

`[23:58:33] [INF] [22] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 60
`

So when the limit of 100 is reached 

`[00:33:59] [INF] [22] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 0
`

The task should end and restart the next day when the quota has been reset. Otherwise, it will just clog the logs and put unnecessary load on the Opensubtitles servers.

```
[00:34:33] [ERR] [20] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: OpenSubtitles download limit reached
[00:34:51] [ERR] [18] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: OpenSubtitles download limit reached
....
[08:48:55] [ERR] [10] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: OpenSubtitles download limit reached
[08:49:02] [ERR] [18] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: OpenSubtitles download limit reached

```

**Comment by crobibero** [comment]
As of right now I don’t believe the server has any way to handle this

**Comment by develroo** [comment]
I am somewhat confused about the server not having some sort of signalling that can tell it a plugin has crashed or got stuck in a loop? That seems positively weird to me. 

If there is some sort of signalling from the plugins to the server, even a  keep alive signal, then it should be trivial either for the plugin to send "Terminate now" or the server to say "Have not heard for X plugin for 5 minutes terminate it" 

So which is it? Is this really so hard to do ?

**Comment by MBR-0001** [comment]
There's no signalling really, when the "download missing subtitles" task is ran the server goes through all libraries and for each episode/movie that is missing a subtitle "tells" the plugin to download it, it doesn't really care if the plugin succeeded or failed, it just keeps going

This _can_ be changed but the server code is quite complex, I should be able to look into it once .NET 6 is fully released

**Comment by develroo** [comment]
Well is is planned in the new factoring? For sure as a programmer and sysadmin the idea of a plugin addon crashing or getting into an infinite loop is a serious oversight and it would be pragmatic and practical to not let plugins gobble up resource (or spam the log).

Let me know if this is a thing because atm the logs are  a mess when you have thousands of titles timing out.

**Comment by oddstr13** [comment]
> Well is is planned in the new factoring? For sure as a programmer and sysadmin the idea of a plugin addon crashing or getting into an infinite loop is a serious oversight and it would be pragmatic and practical to not let plugins gobble up resource (or spam the log).
> 
> Let me know if this is a thing because atm the logs are a mess when you have thousands of titles timing out.

```lua
function download_missing_subtitles_task()
  for movie in library do
    if movie.missing_subtitles then
      -- Prints an error to the log if we can't download the subs right now
      opensubtitles.try_download_subtitle(movie)
    end
  end
end
```

No crashes nor infinite loops, just a scary `[ERR]` in the logs cause we can't right now.
One per attempted and failed subtitle download.

Nothing serious, just noisy in the logs.

---

That aside, would blocking in the opensubtitles plugin until we get a refill be feasible? I'm assuming it runs in it's own async land, and won't actually block anything else by doing this (worst case blocks other subtitle providers?).
