### ISSUE TITLE
Plugin configuration not saving correctly, and gets overwritten on server restart.

### ISSUE THREAD

**Issue by jadonclegg** [jellyfin/jellyfin-plugin-opensubtitles#64]
I can't get the configuration for version 11 to save. If I hit edit plugin, and fill in the settings and save, the page just reloads and clears all the fields, and the xml file in the plugin config directory still has empty elements for the username, password, and api key. If I manually edit the xml file and restart the server, it clears the file. 

I reverted to version 10 and it's working fine with the old API.

**Comment by MBR-0001** [comment]
Can you check if there are any errors in the logs and maybe send a screenshot of the page with network inspector open after clicking on the save button (example below)
![](https://cdn.mbr.pw/51627978106470406.png)

**Comment by jadonclegg** [comment]
When I first load the options page it looks like this.
![image](https://user-images.githubusercontent.com/4791741/132925031-b6f58118-3463-4c2a-9ee5-8778477e8970.png)

This is what it shows in the JS console, it's not even loading the JS to be able to save.
![image](https://user-images.githubusercontent.com/4791741/132925199-c98c8d58-e402-403d-9566-fcf183d0efc8.png)

I do have a reverse proxy set up with Nginx, and I'm running jellyfin in a container. Not sure if that would affect it.

**Comment by jadonclegg** [comment]
I went to the jellyfin documentation website, and the nginx config they suggest using has changed, and I updated the Content-Security-Policy header, and it's working fine now. So it wasn't an issue on your end, thanks for the help!

**Comment by MBR-0001** [comment]
Yeah I assumed it was something like that, glad you solved it!
