### ISSUE TITLE
Plugin Version 12 not available for download in Jellyfin.

### ISSUE THREAD

**Issue by uranderu** [jellyfin/jellyfin-plugin-opensubtitles#71]
There seems something went wrong with your latest release (V12). When I go to the release here on Github and click the [link](https://repo.jellyfin.org/releases/plugin/open-subtitles/open-subtitles_12.0.0.0.zip) it says "Not Found". This makes it that Jellyfin servers don't see the new release.

**Comment by joshuaboniface** [comment]
Should be fixed now, this hit during a wave of plugin release failures in our CI.
