### ISSUE TITLE
Failed to load assembly /config/data/plugins/Open Subtitles_11.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll. Unknown exception was thrown. Disabling plugin.

### ISSUE THREAD

**Issue by NicolasChollet51** [jellyfin/jellyfin-plugin-opensubtitles#80]
Hi everyone, first of all sorry to bother if it is an easy fix i'm not an experienced user. 

My opensubtitles plugin is not working anymore when dowloaded directly from jellyfin plugin catalog. I checked my logs (i'm running Jf in docker) but i didnt see anything at first so i decided to unistall/reinstall the pluggin but after doing so nothing changed: I get this unknow exception that is thrown and nothing else. (logs following). In JF the plugging is marked as "malfunctioned" and I can't put my opensub credentials via user interface. I thought maybe i had to change my credentials in the conf file but i'm lacking of knwoledge with xml and i'm not sure if I wrote it right in the file: I wrote it like this

`<Username="myusername" />
  <Password="mypassword" />`

Anyway I'm lost please help :) 

Thanks a lot in advance

`[16:12:54] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly OpenSubtitlesHandler, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Open Subtitles_11.0.0.0/OpenSubtitlesHandler.dll

[16:12:54] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/data/plugins/Open Subtitles_11.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll. Unknown exception was thrown. Disabling plugin.

System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null'

at System.Reflection.RuntimeAssembly.GetExportedTypes()
at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()`

**Comment by NicolasChollet51** [comment]
11.0, from the catalog it's the latest one but it seemes on the git that it is up to 14 now.

**Comment by MBR-0001** [comment]
that's the plugin version, server version is a different thing (it can be found in the admin dashboard)

**Comment by MBR-0001** [comment]
From the error message it looks like the plugin requires at least 10.7.6

**Comment by crobibero** [comment]
> From the error message it looks like the plugin requires at least 10.7.6

This is correct. Future plugin releases have the correct version requirement so this should be less of an issue. I will check the status of the builds, they should all be in the repo

**Comment by NicolasChollet51** [comment]
Thanks a lot for your replies! Indeed it was a version problem. I dismissed this reason to quick because my docker was showing "up to date", i won't fal in this trap next time and double check on the repo for the version number. I spend a bit of time figuring how to update but now my pluggins is shown as active!

However the pluggin still doestn work but on its setting , when i check the link for api status it is marked as down so i gess it's  a general problem. 

Thanks again
